# Build configuration for Netlify
[build]
  command = "npm run build"
  publish = "dist/invoice-frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
