import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root'
})
export class PdfService {

  constructor() { }

  /**
   * Generate PDF from invoice data
   */
  async generateInvoicePDF(invoice: any): Promise<void> {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      
      // Company Header
      pdf.setFontSize(24);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(40, 116, 166); // Professional blue color
      pdf.text(environment.companyName, pageWidth / 2, 20, { align: 'center' });
      
      // Company Details
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(100, 100, 100);
      let yPos = 28;
      
      if (environment.companyAddress) {
        pdf.text(environment.companyAddress, pageWidth / 2, yPos, { align: 'center' });
        yPos += 5;
      }
      
      let contactInfo = '';
      if (environment.companyPhone) contactInfo += `Phone: ${environment.companyPhone}`;
      if (environment.companyEmail) {
        if (contactInfo) contactInfo += ' | ';
        contactInfo += `Email: ${environment.companyEmail}`;
      }
      if (environment.companyWebsite) {
        if (contactInfo) contactInfo += ' | ';
        contactInfo += `Web: ${environment.companyWebsite}`;
      }
      
      if (contactInfo) {
        pdf.text(contactInfo, pageWidth / 2, yPos, { align: 'center' });
        yPos += 8;
      }
      
      // Separator line
      pdf.setLineWidth(0.5);
      pdf.setDrawColor(200, 200, 200);
      pdf.line(20, yPos, pageWidth - 20, yPos);
      yPos += 10;
      
      // Invoice Title
      pdf.setFontSize(20);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(0, 0, 0);
      pdf.text('INVOICE', pageWidth / 2, yPos, { align: 'center' });
      yPos += 15;
      
      // Invoice details
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      // Invoice number and date
      pdf.text(`Invoice #: ${invoice.invoice_number}`, 20, yPos);
      pdf.text(`Date: ${new Date(invoice.created_at).toLocaleDateString()}`, 20, yPos + 10);
      pdf.text(`Due Date: ${new Date(invoice.due_date).toLocaleDateString()}`, 20, yPos + 20);
      pdf.text(`Status: ${invoice.payment_status?.toUpperCase()}`, 20, yPos + 30);
      
      yPos += 45;
      
      // Customer details
      pdf.setFont('helvetica', 'bold');
      pdf.text('Bill To:', 20, yPos);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`${invoice.customer_name}`, 20, yPos + 10);
      pdf.text(`${invoice.customer_email}`, 20, yPos + 20);
      pdf.text(`${invoice.customer_phone}`, 20, yPos + 30);
      
      if (invoice.customer_address) {
        pdf.text(`${invoice.customer_address}`, 20, yPos + 40);
        yPos += 50;
      } else {
        yPos += 40;
      }
      
      yPos += 20;
      
      // Items table header
      pdf.setFont('helvetica', 'bold');
      pdf.text('Description', 20, yPos);
      pdf.text('Qty', 120, yPos);
      pdf.text('Unit Price', 140, yPos);
      pdf.text('Total', 170, yPos);
      
      // Line under header
      pdf.line(20, yPos + 5, pageWidth - 20, yPos + 5);
      
      // Items
      pdf.setFont('helvetica', 'normal');
      yPos += 15;
      
      if (invoice.invoice_items && invoice.invoice_items.length > 0) {
        invoice.invoice_items.forEach((item: any) => {
          pdf.text(item.description, 20, yPos);
          pdf.text(item.quantity.toString(), 120, yPos);
          pdf.text(`₹${item.unit_price.toFixed(2)}`, 140, yPos);
          pdf.text(`₹${(item.quantity * item.unit_price).toFixed(2)}`, 170, yPos);
          yPos += 10;
        });
      }
      
      // Totals
      yPos += 10;
      pdf.line(120, yPos, pageWidth - 20, yPos);
      yPos += 10;
      
      pdf.text(`Subtotal: ₹${invoice.subtotal?.toFixed(2) || '0.00'}`, 120, yPos);
      yPos += 10;
      pdf.text(`Tax (${invoice.tax_rate || 0}%): ₹${invoice.tax_amount?.toFixed(2) || '0.00'}`, 120, yPos);
      yPos += 10;
      
      pdf.setFont('helvetica', 'bold');
      pdf.text(`Total: ₹${invoice.total?.toFixed(2) || '0.00'}`, 120, yPos);
      
      // Footer
      if (yPos < pageHeight - 50) {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(10);
        pdf.setTextColor(100, 100, 100);
        pdf.text('Thank you for your business!', pageWidth / 2, pageHeight - 30, { align: 'center' });
        pdf.text(`Generated by ${environment.companyName}`, pageWidth / 2, pageHeight - 20, { align: 'center' });
      }
      
      // Save the PDF
      const fileName = `invoice-${invoice.invoice_number || 'draft'}.pdf`;
      pdf.save(fileName);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      throw error;
    }
  }

  /**
   * Generate PDF from HTML element (alternative method)
   */
  async generatePDFFromElement(elementId: string, filename: string = 'invoice.pdf'): Promise<void> {
    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error(`Element with ID '${elementId}' not found`);
      }

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        allowTaint: true
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const imgScaledWidth = imgWidth * ratio;
      const imgScaledHeight = imgHeight * ratio;
      
      const x = (pdfWidth - imgScaledWidth) / 2;
      const y = 10;
      
      pdf.addImage(imgData, 'PNG', x, y, imgScaledWidth, imgScaledHeight);
      pdf.save(filename);
      
    } catch (error) {
      console.error('Error generating PDF from element:', error);
      throw error;
    }
  }
}
